[package]
name = "ticket-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.0"
actix-cors = "0.6.1"
serde = { version = "1.0.152", features = ["derive"] }
futures = "0.3.26"
serde_json = "1.0.93"
tokio = { version = "1.25.0", features = ["sync"] }
